### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by Robdel12**
I used a gem to generate this (and use this in my addons too): https://github.com/skywinder/github-changelog-generator

### CODE REVIEW

**Comment by danielspaniel** [comment]
That was pretty interesting .. never thought of that for auto generating changelog .. but do I then have to update it? I usually update the changes in the release notes.

**Comment by Robdel12** [comment]
You can continue to do both. If you run `github_changelog_generator` in your addon directory it'll use the git info and pull together another changelog :)

**Comment by danielspaniel** [comment]
ok .. great .. good to know

**Comment by Robdel12** [comment]
I'm sure there's a nice way to automate it but I haven't dug into it yet

**Pull request merged**
