### PR TITLE
Changed how to determine if mockjax should be loaded

### PR DESCRIPTION
**Pull request by begedin**
# Description

This PR resolves the issue described in #124 

If the described issue is in fact not an issue, feel free to ignore and close it.

### CODE REVIEW

**Comment by danielspaniel** [comment]
You are right about that one @begedin .. was good catch .. thanks for the PR.

**Comment by danielspaniel** [comment]
v1.3.9 has this change

**Comment by cherewaty** [comment]
Just bumped my Ember CLI app’s `ember-data-factory-guy` version to bring in this change. Now `mockjax` won’t import into my `qunit`-driven acceptance tests in the browser if I simply run `ember server`. The `mockjax` import happens if I run `ember server --environment test`, but then I can't simultaneously run my app on `localhost:4200` and my tests at `localhost:4200/tests`.

I think the original implementation is also how `ember-cli-qunit` determines whether to import its own assets from the `bower` directory (ditto `ember-cli-simple-auth-testing`):
```
if (app.tests) {
  app.import(app.bowerDirectory + '/jquery-mockjax/dist/jquery.mockjax.js');
}
```

**Comment by danielspaniel** [comment]
yikes .. your even more right .. @cherewaty.   What was I thinking before I changed this?? Gulp. That was dumb.  I will comment that to make sure I don't forget again.  Fixing.

**Comment by danielspaniel** [comment]
fixed in  v2.0.3

**Comment by danielspaniel** [comment]
@begedin, until that raven issue is fixed .. you can stay with v2.0.2 I reckon

**Pull request merged**
