### PR TITLE
Adding factories to the app instead

### PR DESCRIPTION
**Pull request by taras**
I don't know if this is the right solution but it seems like it could be. I tried to test it, but the demo app's index.html has all of it's code commented out. Why is that?

### CODE REVIEW

**Comment by danielspaniel** [comment]
You know that is a great question .. why is that index.html code commented out?  I have no idea?

**Comment by taras** [comment]
It looks like you commented it out here https://github.com/danielspaniel/ember-data-factory-guy/commit/3a15f099ba5e8c712f74e95d89c4156d128c7a04

**Comment by danielspaniel** [comment]
Just forgot what was going on there? I will fix that

**Comment by danielspaniel** [comment]
please uncomment that if that helps you test it ..

**Comment by danielspaniel** [comment]
I am testing your idea now

**Comment by danielspaniel** [comment]
not working ..

**Comment by danielspaniel** [comment]
wait .. take that back .. it is in the assets.[appname].js file .. 
 I think the only thing missing now is to require them because they don't get loaded unless they are required .. which is what factory guy manual setup does .. goes through the files and requires them 
 so .. wow .. awesome dude .. I think you did that in 10 minutes ? .. amazing

**Comment by taras** [comment]
:) I'm glad it did the trick. Do you need anything else?

**Comment by danielspaniel** [comment]
yes, can you explain about the microstates sometime to me .. me want to understand more about that .. I don't quite get it

**Comment by taras** [comment]
Let's do a little screenshare and I'll show you how it works.

**Comment by danielspaniel** [comment]
let me know when you want to do that

**Pull request merged**
