### PR TITLE
Issue 213 jsonapi payloadkey

### PR DESCRIPTION
**Pull request by cristinawithout**
For #213

### CODE REVIEW

**Comment by danielspaniel** [comment]
thanks .. @cristinawithout  .. 👍

**Comment by danielspaniel** [comment]
I think this is applicable to the rest converter too .. don't you think?

**Comment by danielspaniel** [comment]
I can hook that up and make a test for it .. so not asking you to do that.

**Comment by cristinawithout** [comment]
Sorry. Missed your replies on this one. I was thinking it might apply to other converters too, but I wasn't sure which.

**Comment by danielspaniel** [comment]
not a big deal, since it is a mixin .. so if anyone peeps up I can add it pretty quickly.
 but I can't think of why you would need for a  delete ? ( because find / query makes no sense )

**Comment by cristinawithout** [comment]
Nah, I can't think of a reason the other types would need match(). Was talking about this older type transform by payload key stuff.

**Comment by cristinawithout** [comment]
You probably already took care of that though.

**Comment by danielspaniel** [comment]
I made it so that payload key was used by all adapters if they had it not just JSONAPI .. maybe it was already like that but I made the tests prove it ( I think ? ) you had just the one test in the JSONAPI adapter custom

**Pull request merged**
