### PR TITLE
Some tweaks to the README

### PR DESCRIPTION
**Pull request by lorcan**
Work in Progress

- Shortening the table of contents
- Putting the "defining factories" stuff together, and before the "using factories" stuff
- Using relative links for the cross-linking (better experience for forks)
- Moved the changelog to the bottom
- Moved the "how this works" nearer the top
- Small tidy-ups and tweaks to the code snippets
- Misc tweaks to other code.

I feel like this could use more eyes :-)

More context from earlier discussions over at https://github.com/lorcan/ember-data-factory-guy/pull/1

### CODE REVIEW

**Comment by danielspaniel** [comment]
I will pull this branch and check it out

**Comment by danielspaniel** [comment]
I think it all looks fine Lorcan.  I see no problem with merging this when you feel like you are all set.

**Comment by lorcan** [comment]
👍  if you're happy, I'm happy

**Comment by danielspaniel** [comment]
Thanks for making this effort Lorcan. The docs are super important, and it is great that you took the time to make it better.

**Pull request merged**
