### PR TITLE
Update README to reflect mockTeardown() usage in component tests

### PR DESCRIPTION
**Pull request by oniofchaos**
Addresses answer to https://github.com/danielspaniel/ember-data-factory-guy/issues/224

I just noticed my Vim settings stripped out all the extra whitespace in the README. Let me know if you want me to revert those portions.

### CODE REVIEW

**Comment by danielspaniel** [comment]
Ooops. I think I mistakenly gave the impression that I forgot to put the afterEach() mockTeardown in the moduleForComponent and moduleForModel tests. 

What I meant was .. 

 oops .. I forgot to tell people that if they are going to use mocking in component and model tests ( rare ..but I do it myself ) .. that they need to add mockSetup, mockTeardown. 
 
 Sorry about that .. I think all you have to do is add to the readme and maybe setup up a test if you want that uses the mocks ( component or model ) ..

 but it has to be clear that if you just make or makeList or build/ buildList .. you don't need mockSetup/mockTeardown 

 know what I mean?

**Comment by oniofchaos** [comment]
I'm not sure what you mean, actually :)

If I'm using `make` in a component test and don't include `manualSetup(this.container)`, the test fails. 

Are you suggesting that `mockSetup()` should be used instead of `manualSetup(this.container)`?

**Comment by danielspaniel** [comment]
No, 
 what I mean is:
 
 for moduleForComponent or moduleForModel tests
 you only need need need manualSetup(this.container)

 and by any chance you are doing mock this or that then you 
 need the mockSetup, mockTeardown

 your documentation is showing you ALWAYS need mockSetup, mockTeardown.

 see what I mean?

**Comment by oniofchaos** [comment]
Ok, check that out.

**Comment by danielspaniel** [comment]
sold .. thanks for listening and getting this right. 👍

**Pull request merged**
