### PR TITLE
handleFindAll() and buildList() can make diverse models

### PR DESCRIPTION
**Pull request by afn**
The `handleFindAll` function is a bit lacking in that all of the models it generates are identical (except for sequences).  This PR allows it to be called with a list of traits/options instead of a number.

```javascript
// findAll('user') will return Alice, Bob, and Charlotte (who is an admin)
TestHelper.handleFindAll('user', {name: 'Alice'}, {name: 'Bob'}, ['admin', {name: 'Charlotte'}]);
```

### CODE REVIEW

**Comment by afn** [comment]
That's right: if the second argument is not a number, then it's assumed that the second and subsequent arguments are the specification for each model.  Each of these arguments can be an array `['trait1', 'trait2', {key: 'value'}]`, an object `{key: 'value'}`, or a single trait `'trait1'`.

**Comment by danielspaniel** [comment]
This clearly is a fun feature. So thanks for the great idea. Can you add a few more tests ( you have one I think ) .. need one or two for handleFindAll  and then change the README to show the new feature ..

**Comment by afn** [comment]
@danielspaniel How does that look?

**Comment by danielspaniel** [comment]
Pretty good mate .. thanks! :)

**Comment by afn** [comment]
Thanks for merging this so quickly! Are you planning a new release soon?

**Comment by danielspaniel** [comment]
Yes, I will do this today ( I was wondering when you would ask .. so thanks for the nudge ). Was waiting to do other upgrades, but I am taking too long.

**Pull request merged**
