### PR TITLE
Handle active model formatted request data properly

### PR DESCRIPTION
**Pull request by ccleung**
convert the root key from `my-model-name` to `my_model_name` so that we access the data properly.

See issue https://github.com/danielspaniel/ember-data-factory-guy/issues/165 for more detail

### CODE REVIEW

**Comment by danielspaniel** [comment]
This was good idea .. 
Overall I am a bit sad about mockCreate .. it needs some lovin' .. even more than you have given it .. so if you have any other good ideas .. send em my way!
One more thing, this does pass tests .. but do you you think you could add one to show that this works so it does not get broken in the future?

**Comment by ccleung** [comment]
@danielspaniel added tests in updated commit

**Comment by danielspaniel** [comment]
with added tests, the build is failing for some reason .. can you check it out?

**Comment by ccleung** [comment]
yeah it looks like DS.RESTAdapter test is failing because the root key is `camelCase` instead of `under_score`

**Comment by danielspaniel** [comment]
I thought that might happen .. if it's not easy to fix I can help out later today.

**Comment by ccleung** [comment]
seems like there is no difference between ActiveModelAdapter and RESTAdapter now? https://github.com/danielspaniel/ember-data-factory-guy/blob/master/addon/builder/fixture-builder-factory.js , im trying to figure out how to differentiate the two cases...

**Comment by danielspaniel** [comment]
They both do the same thing, but they are calling out to get a tranformer for an attribute ( lets say ) .. and that will depend on the adapter type, but the two fixture builders don't have to know what that is. So, for you, you need the payload key ( or something like that ) .. so maybe try and ask the fixtureBuilder ( add a method ? )  because it has the adapter all setup, and then  maybe adapter.payloadKey(modelName)  might do it.  ??

**Comment by ccleung** [comment]
yeah ill try that thanks

**Comment by ccleung** [comment]
Doesn't look like the adapter class has any methods for figuring out the root key, seems like something i can put into fixtureBuilder classes themselves, but that means that we may need to introduce an ActiveModelFixtureBuilder instance, that will have a 'payloadKey' that works differently from RESTFixtureBuilder, would that be okay? ActiveModelFixtureBuilder will extend RESTFixtureBuilder and the only different would be the implementation of the new `payloadKey` method

**Comment by danielspaniel** [comment]
Sorry .. I was wrong about adapter, it's serializer

http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_payloadKeyFromModelName

**Comment by ccleung** [comment]
@danielspaniel updated, thanks for the feedback and help

**Comment by danielspaniel** [comment]
Thanks for hanging in there! :)

**Pull request merged**
