### PR TITLE
[WIP] Handle update

### PR DESCRIPTION
**Pull request by pedrokiefer**
This is a basic implementation of what we discussed on #60. I'm open to suggestions, but I think this is a good starting point.

### CODE REVIEW

**Comment by danielspaniel** [comment]
wow .. @pedrokiefer .. I am glad you finally got around to this .. give me a day to look it over .. but so far, looks like good start.

**Comment by danielspaniel** [comment]
Ok @pedrokiefer ... first question .. did you write a test for the problem this new code solves. 
  I am alittle unclear how/what this is doing differently ( except for the chainable methods part ( which is nice ) ) than the old code.  I guess I am not sure what this does different than before is what I am saying.

**Comment by pedrokiefer** [comment]
It solves the issue I was having with ember-data 14.1, tests in the project I'm working were **failing** because the mocked ajax was **not returning data**. After updating to my branch, all tests passed.

Right now it should not do anything else as the old code, expect returning a json object on the mocked ajax call. But this new code allows us to do things like custom failure codes with different response text, mock a timeout, and maybe some other scenarios. I'll add tests and use cases for this shortly.

**Comment by pedrokiefer** [comment]
The error I was getting is the following:

```
Error: Assertion Failed: An adapter cannot assign a new id to a record that already has an id. <my-project@model:something::ember895:1> had id: 1 and you tried to update it with null. This likely happened because your server returned data in response to a find or update that had a different id than the one you sent.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:22910:23)
    at Object.Ember.assert (http://localhost:4200/assets/vendor.js:14407:15)
    at Ember.Object.extend.updateId (http://localhost:4200/assets/vendor.js:78982:15)
    at Ember.Object.extend.didSaveRecord (http://localhost:4200/assets/vendor.js:78933:16)
    at http://localhost:4200/assets/vendor.js:79736:17
    at Object.Backburner.run (http://localhost:4200/assets/vendor.js:10667:27)
    at ember$data$lib$system$store$$_adapterRun (http://localhost:4200/assets/vendor.js:79568:32)
    at http://localhost:4200/assets/vendor.js:79730:9
    at tryCatch (http://localhost:4200/assets/vendor.js:60908:16)
```

After updating I don't get any errors and my tests passes :)

**Comment by danielspaniel** [comment]
Ok @pedrokiefer, thanks for adding more tests (  if all the possibilities are covered I'd be happy ) .. and perhaps you can fix up the documentation a show these changes to handleUpdate ?? and I will merge this.

**Comment by pedrokiefer** [comment]
@danielspaniel just added the new docs for handleUpdate, please review it :)

**Comment by danielspaniel** [comment]
Me like :) .. thanks for being thorough with docs and tests

**Pull request merged**
