### PR TITLE
Add handleFindOne method

### PR DESCRIPTION
**Pull request by Marthyn**
to handle get requests with a specific id.

like

```
/api/v1/profiles/1
```

will return a record with id 1.

### CODE REVIEW

**Comment by danielspaniel** [comment]
@Marthyn .. can you give me use case for the handleFindOne .. it's interesting because I think I used to have that method, but I took it out a long time ago because I thought people could do:
```
FactoryGuy.make('user');
store.find('user', user.id).then(function(user) { // blah });
```
for this case.

**Comment by Marthyn** [comment]
True, but for example a reload on that object will still trigger an api request. I found in our app that even though we created the object with factoryguy there were still requests occurring, which we used to catch with pretender but we want to switch.

**Comment by danielspaniel** [comment]
Oh boy .. totally forgot about reload .. got it.

**Comment by danielspaniel** [comment]
Are you using bower? If so you can get this code by updating since its now in master branch. If not (using gem) let me know and I will make new release version.

**Comment by danielspaniel** [comment]
@Marthyn .. and thanks for updating the readme documentation ( almost no one does that )

**Comment by Marthyn** [comment]
We're using the gem :)

**Comment by danielspaniel** [comment]
v0.9.4 gem  is now ready

**Comment by Marthyn** [comment]
Thanks! Another use case i found btw is this:

`self.transitionToRoute('chapter', self.get('model.id'));`

you transition to the id of an object, instead of to the object itself. So it forces a reload.

**Comment by danielspaniel** [comment]
Interesting .. I have never done that in a transition .. only passed model .. good to know.

**Pull request merged**
