### PR TITLE
Fix handling of non-model-fragment hashes

### PR DESCRIPTION
**Pull request by mreq**
Regular hash objects didn't work before

    model-definition.js:50 Uncaught TypeError: Cannot read property 'match' of undefined

Example hash:

```coffee
FactoryGuy.define 'modelName',
  default:
    foo: { bar: true }
```

### CODE REVIEW

**Comment by danielspaniel** [comment]
Thanks for the PR .. good catch .. and can add a test for this .. ??

**Comment by mreq** [comment]
can do, will update once I get some time

**Comment by iraspopo** [comment]
I run into this issue and was wondering when this fix will be available (merged in)?

**Comment by danielspaniel** [comment]
I will work on this one today .. might be able to wrap it up .. stay tuned

**Comment by danielspaniel** [comment]
Question .. what version of factory guy you on ..I just wrote a test for this and it works fine to use hash at attribute for non model fragment. 

 You will have to update factory guy ( and rerun that test ) 
  or send me your model, and your factory and your test that is failing so i can try and recreate it

**Comment by danielspaniel** [comment]
Never mind .. I found the bug .. you have to pass in the hash in the build options .. ok .. I am all set

**Comment by danielspaniel** [comment]
I have this fixed .. will release tomorrow

**Comment by danielspaniel** [comment]
Fixed in new patch version:  
 https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.8.1

**Pull request closed without merging**
